// Generated by CoffeeScript 1.8.0

/*!
sarine.viewer.dynamic.light.sprite - v1.0.0 -  Monday, August 1th, 2016, 10:53:01 AM 
 The source code, name, and look and feel of the software are Copyright © 2015 Sarine Technologies Ltd. All Rights Reserved. You may not duplicate, copy, reuse, sell or otherwise exploit any portion of the code, content or visual design elements without express written permission from Sarine Technologies Ltd. The terms and conditions of the sarine.com website (http://sarine.com/terms-and-conditions/) apply to the access and use of this software.
 */
var LightSprite,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

LightSprite = (function(_super) {
  __extends(LightSprite, _super);

  function LightSprite(options) {
    LightSprite.__super__.constructor.call(this, options);
  }

  LightSprite.prototype.convertElement = function() {
    return this.element;
  };

  LightSprite.prototype.first_init = function() {
    var defer;
    defer = $.Deferred();
    defer.resolve(this);
    return defer;
  };

  LightSprite.prototype.full_init = function() {
    var defer;
    defer = $.Deferred();
    defer.resolve(this);
    return defer;
  };

  LightSprite.prototype.play = function() {};

  LightSprite.prototype.stop = function() {};

  return LightSprite;

})(Viewer);

this.LightSprite = LightSprite;
